# Generated by Django 5.2.6 on 2025-12-02 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BajoRecursos',
            fields=[
                ('id_bajo', models.AutoField(primary_key=True, serialize=False)),
                ('ciudad', models.CharField(max_length=50)),
                ('donacion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'bajo_recursos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Donaciones',
            fields=[
                ('id_donacion', models.AutoField(primary_key=True, serialize=False)),
                ('donante', models.CharField(db_column='Donante', max_length=255)),
                ('cantidad', models.IntegerField()),
                ('fecha_llegada', models.DateField()),
                ('tipo_alimento', models.CharField(max_length=50)),
                ('destino', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'donaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Donante',
            fields=[
                ('id_donante', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_donante', models.CharField(blank=True, max_length=12, null=True)),
                ('ciudad', models.CharField(max_length=255)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=10, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'db_table': 'donante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoDeAlimento',
            fields=[
                ('id_tipo', models.AutoField(db_comment='Identificador único autoincremental del tipo de alimento', primary_key=True, serialize=False)),
                ('perecible', models.CharField(db_comment='Indica si el alimento es perecible (1=Sí, 0=No)', max_length=50)),
                ('no_perecibles', models.CharField(db_comment='Indica si el alimento es no perecible (1=Sí, 0=No)', max_length=50)),
                ('estado', models.CharField(db_comment='Estado del alimento (1=Bueno, 2=Regular, 3=Malo)', max_length=50)),
                ('fecha_caducidad', models.DateField(db_comment='Fecha de caducidad representada como entero')),
            ],
            options={
                'db_table': 'tipo_de_alimento',
                'db_table_comment': 'Tabla para almacenar tipos de alimentos con información sobre perecibilidad y estado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zoo',
            fields=[
                ('id_zoo', models.AutoField(primary_key=True, serialize=False)),
                ('animales', models.CharField(max_length=255)),
                ('trabajadores', models.CharField(max_length=255)),
                ('tipo_animal', models.CharField(max_length=50)),
                ('donacion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'zoo',
                'managed': False,
            },
        ),
    ]
