# Generated by Django 5.2.6 on 2025-10-14 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BajoRecursos',
            fields=[
                ('id_bajo', models.AutoField(primary_key=True, serialize=False)),
                ('ciudad', models.IntegerField()),
                ('donacion', models.IntegerField()),
            ],
            options={
                'db_table': 'bajo_recursos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Donaciones',
            fields=[
                ('id_donacion', models.AutoField(primary_key=True, serialize=False)),
                ('donante', models.CharField(db_column='Donante', max_length=255)),
                ('cantidad', models.IntegerField()),
                ('fecha_llegada', models.IntegerField()),
                ('tipo_alimento', models.IntegerField()),
                ('destino', models.IntegerField()),
            ],
            options={
                'db_table': 'donaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Donante',
            fields=[
                ('id_donante', models.AutoField(primary_key=True, serialize=False)),
                ('ciudad', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'donante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoDeAlimneto',
            fields=[
                ('id_tipo', models.AutoField(db_comment='Identificador único autoincremental del tipo de alimento', primary_key=True, serialize=False)),
                ('perecible', models.IntegerField(db_comment='Indica si el alimento es perecible (1=Sí, 0=No)')),
                ('no_perecibles', models.IntegerField(db_comment='Indica si el alimento es no perecible (1=Sí, 0=No)')),
                ('estado', models.IntegerField(db_comment='Estado del alimento (1=Bueno, 2=Regular, 3=Malo)')),
                ('fecha_caducidad', models.IntegerField(db_comment='Fecha de caducidad representada como entero')),
            ],
            options={
                'db_table': 'tipo_de_alimneto',
                'db_table_comment': 'Tabla para almacenar tipos de alimentos con información sobre perecibilidad y estado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zoo',
            fields=[
                ('id_zoo', models.AutoField(primary_key=True, serialize=False)),
                ('animales', models.CharField(max_length=255)),
                ('trabajadores', models.CharField(max_length=255)),
                ('tipo_animal', models.IntegerField()),
                ('donacion', models.IntegerField()),
            ],
            options={
                'db_table': 'zoo',
                'managed': False,
            },
        ),
    ]
