# Generated by Django 5.2.6 on 2025-11-10 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appDonaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bajorecursos',
            options={},
        ),
        migrations.AlterModelOptions(
            name='donaciones',
            options={},
        ),
        migrations.AlterModelOptions(
            name='donante',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tipodealimneto',
            options={},
        ),
        migrations.AlterModelOptions(
            name='zoo',
            options={},
        ),
    ]
