"""
Django settings for prjDonaciones project.

Generated by 'django-admin startproject' using Django 5.2.6.
"""

import os
import dj_database_url
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-cr+jojr%0gh%1k6hw#yd^s)no(m6csw@yazu&!h5)g4l-b%^2@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Permitir cualquier host (necesario para Render)
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'appDonaciones',
    'django_recaptcha', # Tu app de Captcha
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # Para estilos en la nube
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'prjDonaciones.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "template"], # Asegúrate de que tu carpeta se llame 'template' en la raíz
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'prjDonaciones.wsgi.application'


# Database
# Por defecto usa MySQL (Local). Si detecta Render, cambia a PostgreSQL.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'donaciones',
        'USER': 'root',
        'PASSWORD': 'admin',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}

# Configuración para Render (Base de datos en la nube)
# Esto sobreescribe la configuración anterior si estamos en el servidor de Render
database_url = os.environ.get("DATABASE_URL")
if database_url:
    DATABASES["default"] = dj_database_url.parse(database_url)


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    { 'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator', },
]


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'

# Configuración para que Whitenoise maneje los estilos en producción
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [BASE_DIR / "static"]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# --- CONFIGURACIÓN DE LOGIN Y SESIÓN ---
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
LOGIN_URL = 'signin'

SESSION_COOKIE_AGE = 1800 # 30 minutos
SESSION_SAVE_EVERY_REQUEST = True


# --- CONFIGURACIÓN DE CORREO (GMAIL) ---
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# Tus credenciales
EMAIL_HOST_USER = 'matias.gregorio5635@gmail.com' 
EMAIL_HOST_PASSWORD = 'wuuqykrcxpdxgbcr' 

DEFAULT_FROM_EMAIL = 'Sistema de Donaciones <matias.gregorio5635@gmail.com>'


# --- CONFIGURACIÓN DE RECAPTCHA ---
RECAPTCHA_PUBLIC_KEY = '6Lf5dx4sAAAAAJwcqq73wgZHAki59_b321JlsMx0'
RECAPTCHA_PRIVATE_KEY = '6Lf5dx4sAAAAAHSgifDFDZpVNp45qQNe0cZPuv7c'

# Evitar errores de SSL en localhost (entorno de desarrollo)
OS_ENV = os.environ.get('OS_ENV', 'development')
if OS_ENV == 'development':
    RECAPTCHA_use_ssl = False